#ifndef API_EMBEDDED_ASSETS_H
#define API_EMBEDDED_ASSETS_H

#include <stddef.h>

/* Pre-compressed frontend assets embedded at build time.
 * Generated by scripts/embed_frontend.sh from frontend/dist/. */

typedef struct {
    const char          *path;         /* URL path, e.g. "/index.html" */
    const unsigned char *data;         /* raw file content */
    size_t               size;
    const unsigned char *data_gz;      /* gzip-compressed, NULL if skipped */
    size_t               size_gz;
    const unsigned char *data_br;      /* brotli-compressed, NULL if skipped */
    size_t               size_br;
    const char          *content_type;
} embedded_asset_t;

/* Look up an embedded asset by URL path. Returns NULL if not found. */
const embedded_asset_t *embedded_assets_find(const char *url);

#endif
