#!/usr/bin/env bash
#
# embed_frontend.sh — Generate embedded_assets.c from frontend/dist/
#
# For each file: emit raw bytes via xxd, plus gzip and brotli variants
# when compression achieves >= 10% reduction. Output is a single C file
# with a lookup table for the HTTP server.
#
# Usage: scripts/embed_frontend.sh frontend/dist > build/embedded_assets.c

set -euo pipefail

DIST_DIR="${1:?Usage: $0 <dist-dir>}"

if [ ! -d "$DIST_DIR" ]; then
    echo "error: $DIST_DIR does not exist (run 'make frontend' first)" >&2
    exit 1
fi

# Map file extension to MIME type
content_type_for() {
    case "${1##*.}" in
        html) echo "text/html" ;;
        js)   echo "application/javascript" ;;
        css)  echo "text/css" ;;
        json) echo "application/json" ;;
        png)  echo "image/png" ;;
        svg)  echo "image/svg+xml" ;;
        ico)  echo "image/x-icon" ;;
        *)    echo "application/octet-stream" ;;
    esac
}

# Turn a file path into a valid C identifier
c_ident() {
    echo "$1" | sed 's|[^a-zA-Z0-9]|_|g' | sed 's|^_*||'
}

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

# Collect files
mapfile -t FILES < <(find "$DIST_DIR" -type f | sort)

if [ ${#FILES[@]} -eq 0 ]; then
    echo "error: no files found in $DIST_DIR" >&2
    exit 1
fi

# --- Header ---
cat <<'HEADER'
/* Auto-generated by scripts/embed_frontend.sh — do not edit */
#include "api/embedded_assets.h"
#include <string.h>

HEADER

# --- Per-file: raw + compressed byte arrays ---
declare -a ENTRIES

for filepath in "${FILES[@]}"; do
    relpath="${filepath#"$DIST_DIR"/}"
    url_path="/$relpath"
    ident=$(c_ident "$relpath")
    ct=$(content_type_for "$relpath")
    raw_size=$(stat -c%s "$filepath")

    # Raw bytes
    echo "static const unsigned char asset_${ident}_raw[] = {"
    xxd -i < "$filepath"
    echo "};"
    echo ""

    # Gzip
    gz_var="NULL"
    gz_size="0"
    gzip -9 -c "$filepath" > "$TMPDIR/gz"
    gz_actual=$(stat -c%s "$TMPDIR/gz")
    reduction=$(( (raw_size - gz_actual) * 100 / (raw_size > 0 ? raw_size : 1) ))
    if [ "$reduction" -ge 10 ]; then
        echo "static const unsigned char asset_${ident}_gz[] = {"
        xxd -i < "$TMPDIR/gz"
        echo "};"
        echo ""
        gz_var="asset_${ident}_gz"
        gz_size="$gz_actual"
    fi

    # Brotli
    br_var="NULL"
    br_size="0"
    brotli -9 -c "$filepath" > "$TMPDIR/br"
    br_actual=$(stat -c%s "$TMPDIR/br")
    reduction=$(( (raw_size - br_actual) * 100 / (raw_size > 0 ? raw_size : 1) ))
    if [ "$reduction" -ge 10 ]; then
        echo "static const unsigned char asset_${ident}_br[] = {"
        xxd -i < "$TMPDIR/br"
        echo "};"
        echo ""
        br_var="asset_${ident}_br"
        br_size="$br_actual"
    fi

    # Log to stderr
    echo "  [EMBED] $url_path: ${raw_size}b raw" \
         "gz:${gz_size}b br:${br_size}b" >&2

    ENTRIES+=("    { \"$url_path\", asset_${ident}_raw, $raw_size, $gz_var, $gz_size, $br_var, $br_size, \"$ct\" },")
done

# --- Lookup table ---
echo "static const embedded_asset_t assets[] = {"
for entry in "${ENTRIES[@]}"; do
    echo "$entry"
done
echo "    { NULL, NULL, 0, NULL, 0, NULL, 0, NULL }"
echo "};"
echo ""

# --- Find function ---
cat <<'FIND'
const embedded_asset_t *embedded_assets_find(const char *url)
{
    for (const embedded_asset_t *a = assets; a->path; a++) {
        if (strcmp(a->path, url) == 0)
            return a;
    }
    return NULL;
}
FIND
